### Obtener Datos
GET http://localhost:1234/pokemon/ditto

### Crear Recurso
POST http://localhost:1234/pokemon
Content-Type: application/json

{
    "name": "ditto",
    "type": "normal",
    "moves": [
        "transform"
    ]

}
